config/routes.rb
Rails.application.routes.draw do
  # get 'welcome/index' tells Rails to map requests 
  # to http://localhost:3000/welcome/index to the welcome controller's index action. 
  # This was created earlier when you ran the controller generator (rails generate controller Welcome index).
  get 'welcome/index'

  # Rails provides a resources method which can be used to declare a standard REST resource. 
  # You need to add the article resource to the config/routes.rb so the file will look as follows:
  # resources :articles
  resources :articles do
    resources :comments
  end

  resources :users do
    resources :comments
  end


  # root 'welcome#index' tells Rails to map requests to the root of the application to the 
  # welcome controller's index action and ''
  root 'welcome#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments, dependent: :nullify
    belongs_to :user
    validates :title, presence: true,
                      length: { minimum: 5 }

    def author(return_id: false)
        return "N/A" unless user_id.present?
        return_id ? user_id : user.name
    end

    
    # helper_method :article_author
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
  # validates :user, presence: true,
  # validates :body, presence: true,
  #                     length: { minimum: 3 }                      

  # we use this instead of comment.user.name because this can return N/A
  def author(return_id: false)  
    return "N/A" unless user_id.present?
    return_id ? user_id : user.name
  end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :article, dependent: :nullify
    has_many :comment, dependent: :nullify
    validates :name, presence: true,
                      length: { minimum: 3 }

    before_save :make_logo

    def make_logo 
        self.name = name.titleize
        names_array = name.gsub(/\s+/m, ' ').strip.split(" ")
        self.letter = names_array.map { |n| n[0] }.join
    end
    
    
end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Need a way to find out how to do this without hard coding the first user
    
    def current_user
        User.last 
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
 
    def index 
        @articles = Article.all
    end
    
    def show
        @article = Article.find(params[:id])
    end

    def new
        @current_user = current_user
        @article = Article.new
    end

    def create
        @article = Article.new(article_params)
        @article.user_id = current_user.id
        
        if @article.save
            redirect_to @article
        else
            render 'new'
        end
    end

    def edit
        @article = Article.find(params[:id])
    end
    
    def update
        @article = Article.find(params[:id])
       
        if @article.update(article_params)
          redirect_to @article
        else
          render 'edit'
        end
    end

    def destroy
      @article = Article.find(params[:id])
      @article.destroy
     
      redirect_to articles_path
    end
    
    private
    def article_params
        params.require(:article).permit(:title, :text)
    end

  end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy    
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params) 
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
 
  private
    def comment_params
      params.require(:comment)
            .permit(:body)  # we want to merge the user_id into params
            .merge(user_id: current_user.id)

    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index 
    @users = User.all
  end

  def show
      @user = User.find(params[:id])
  end

  def new
      @user = User.new
  end

  def create
      @user = User.new(user_params)

      if @user.save
          redirect_to @user
      else
          render 'new'
      end
  end

  def edit
      @user = User.find(params[:id])
  end

  def update
      @user = User.find(params[:id])
    
      if @user.update(user_params)
        redirect_to @user
      else
        render 'edit'
      end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
  
    redirect_to users_path
  end
 
  private
    def user_params
      params.require(:user).permit(:name, :letter)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>
 
    <% if @article.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@article.errors.count, "error") %> prohibited
          this article from being saved:
        </h2>
        <ul>
          <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
   
    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </p>
   
    <p>
      <%= form.label :text %><br>
      <%= form.text_area :text %>
    </p>
   
    <p>
      <%= form.submit %>
    </p>
   
  <% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing Articles</h1>
<h2><%= link_to 'Create New Article', new_article_url %></h2>
 
<table style="width: 100%">
  <tr>
    <th>Article ID</th>
    <th>Title</th>
    <th>Text</th>
    <th>Author ID</th>
    <th>Author</th>
    <th></th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.id %></td>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= article.author(return_id: true) %></td>
      <td><%= article.author %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article),
            method: :delete,
            data: { confirm: 'Are you sure?' } %></td>
    
  <% end %>
  </tr>
      <tr>
      <th>Article ID</th>
      <th>Title</th>
      <th>Text</th>
      <th>Author ID</th>
      <th>Author</th>
      <th></th>
    </tr>
</table>
<%= link_to 'Back', welcome_index_url %>

app/views/articles/new.html.erb
<h1>New Article</h1>
<h2>
  <strong>You:</strong>
  <%= @current_user.name %>
</h2>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<h2>Review</h2>
<p>
  <strong>Author:</strong>
  <%= @article.user.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
 
<h2>Comments</h2>
<%= render @article.comments %>
 
<h2>Add a comment:</h2>
<%= render 'comments/form' %>
 
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<p>
  <strong><%= comment.user.name %> (#   
  <%=comment.user_id%>):  </strong>
  <%= comment.body %>
</p>
 
<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
    <p>
      <%= form.label :body %><br>
      <%= form.text_area :body %>
    </p>
    <p>
      <%= form.submit %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with model: @user, local: true do |form| %>
 
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@user.errors.count, "error") %> prohibited
          this user from being saved:
        </h2>
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
   
    <p>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
    </p>
  
   
    <p>
      <%= form.submit %>
    </p>
   
  <% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing Users</h1>
<h2><%= link_to 'Create User', new_user_url %></h2>

<table>
  <tr>
    <th>Name</th>
    <th>Initials</th>
    <th></th>
  </tr>
 
  <% @users.each do |u| %>
    <tr>
      <td><%= u.name %></td>
      <td><%= u.letter %></td>
      <td><%= link_to 'Show', user_path(u) %></td>
      <td><%= link_to 'Edit', edit_user_path(u) %></td>
      <td><%= link_to 'Destroy', user_path(u),
            method: :delete,
            data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'Back', welcome_index_url %>

app/views/users/new.html.erb
<h1>New User</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Initials:</strong>
  <%= @user.letter %>
</p>
 
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<h1>Nalin's Blog Thing</h1>
<h2><%= link_to 'Articles', controller: 'articles' %> | 
<%= link_to 'Users', controller: 'users' %></h2>